### ISSUE TITLE
How do I fix a 32 gb flash drive that shows less than actual storage space?

### ISSUE THREAD

**Issue by maxmod** [usbtool/formatusb#1]
How do I fix a flash drive that shows less than actual storage space?
32 GB USB flash drive capacity down to 900 MB
![lUVdt](https://user-images.githubusercontent.com/25316260/119343602-4b655780-bcb4-11eb-89ce-4f92cfbe3808.png)

**Comment by usbtool** [comment]
> How do I fix a flash drive that shows less than actual storage space?
> 32 GB USB flash drive capacity down to 900 MB
> ![lUVdt](https://user-images.githubusercontent.com/25316260/119343602-4b655780-bcb4-11eb-89ce-4f92cfbe3808.png)

Download this software from https://formatusb.com/ or  https://github.com/usbtool/formatusb/releases
Closing the issue
Thank You
